/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud.vistas;

import javax.swing.JFrame;

/**
 *
 * @author shinigamicorei7
 */
public class Main extends JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenu = new javax.swing.JToolBar();
        javax.swing.ImageIcon UsersII = new javax.swing.ImageIcon(getClass().getResource("/crud/recursos/img/Usuarios.png"));
        java.awt.Image UsersIcon = UsersII.getImage();
        showUsuarios = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD Simple");
        setExtendedState(6);

        MainMenu.setFloatable(false);
        MainMenu.setRollover(true);

        showUsuarios.setIcon(new javax.swing.ImageIcon(UsersIcon.getScaledInstance(64, 64, java.awt.Image.SCALE_SMOOTH)));
        showUsuarios.setText("Usuarios");
        showUsuarios.setFocusable(false);
        showUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        showUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MainMenu.add(showUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
            .addComponent(jDesktopPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar MainMenu;
    public javax.swing.JDesktopPane jDesktopPane2;
    public javax.swing.JButton showUsuarios;
    // End of variables declaration//GEN-END:variables

    
}
